config/routes.rb
Rails.application.routes.draw do
  resources :peer_teacher_logins
  resources :administrators
  ActiveAdmin.routes(self)
  
  devise_for :users, skip: :registrations, controllers: {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
    end
      
    get 'users/sign_out' => 'users/sessions#destroy'
    get 'users/sign_in'  => 'home#index'
    get 'users/password/edit' => 'users/password#edit'
  end
  
  get 'login_hub/index'                 #the index is for the regular user 
  get 'login_hub/admin'                 #for the admin page 
  
  get 'home/index'
  get 'home/populate_db'
  get 'home/availables'
  
  get '/ptc', to: 'ptc#ptc'
  get '/admin', to: 'admin#admin'
  get '/pt', to: 'pt#pt'

  root 'home#index' 

      resources :peer_teachers
      resources :office_hours
      resources :updates

end

app/models/peer_teacher_login.rb
class PeerTeacherLogin < ActiveRecord::Base
    has_one :user, as: :meta, dependent: :destroy 
    accepts_nested_attributes_for :user
    
    validates :first_name, presence: true
    validates :last_name, presence: true 
end

app/controllers/peer_teacher_logins_controller.rb
class PeerTeacherLoginsController < InheritedResources::Base
#GET /login_user
    def index 
       @peer_teacher_login = PeerTeacherLogin.all  
    end

    #GET /peer_teacher_login
    def show 
    end
    
    # GET /peer_teacher_login/new
    def new 
       @peer_teacher_login = PeerTeacherLogin.new
       @peer_teacher_login.build_user
    end
    
    # GET /peer_teacher_login/1/edit 
    def edit
    end
    
    # POST /peer_teacher_login
    def create 
       @peer_teacher_login = PeerTeacherLogin.new(peer_teacher_login_params)
       
        respond_to do |format|
            if @peer_teacher_login.save
                format.html { redirect_to root_path, notice: 'Peer Teacher User was successfully created.' }
                format.json { render :show, status: :created, location: @peer_teacher_login }
            else
                format.html { render :new }
                format.json { render json: @peer_teacher_login.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /login_user/1
    def update
        respond_to do |format|
          if @peer_teacher_login.update(peer_teacher_login_params)
            format.html { redirect_to @peer_teacher_login, notice: 'Peer Teacher User was successfully updated.' }
            format.json { render :show, status: :ok, location: @peer_teacher_login }
          else
            format.html { render :edit }
            format.json { render json: @peer_teacher_login.errors, status: :unprocessable_entity }
          end
        end
    end
    
    # DELETE /admnistrators/1 
    def destroy 
        @peer_teacher_login.destroy
        respond_to do |format|
            format.html { redirect_to teachers_url, notice: 'Peer Teacher User was successfully destroyed.' }
            format.json { head :no_content }
        end 
    end

  private
    
    def set_administrator
       @peer_teacher_login = PeerTeacherLogin.find( params[:id] ) 
    end

    def peer_teacher_login_params
        params.require(:peer_teacher_login).permit(:first_name, :last_name, user_attributes: [:id, :email, :password, :password_confirmation ])
    end
    
    def authenticate_administrator
        redirect_to( new_user_session_path) unless current_user.meta_type == "PeerTeacherLogin"
    end
    
    def new_registration
       redirect_to( login_user_path ) if user_signed_in?  
    end
end

app/helpers/peer_teacher_logins_helper.rb
module PeerTeacherLoginsHelper
end

app/views/peer_teacher_logins/_form.html.erb
<%= form_for(@peer_teacher_login) do |f| %>
  <% if @peer_teacher_login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peer_teacher_login.errors.count, "error") %> prohibited this peer_teacher_login from being saved:</h2>

      <ul>
      <% @peer_teacher_login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peer_teacher_logins/edit.html.erb
<h1>Editing Peer Teacher Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @peer_teacher_login %> |
<%= link_to 'Back', peer_teacher_logins_path %>

app/views/peer_teacher_logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peer Teacher Logins</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peer_teacher_logins.each do |peer_teacher_login| %>
      <tr>
        <td><%= peer_teacher_login.first_name %></td>
        <td><%= peer_teacher_login.last_name %></td>
        <td><%= link_to 'Show', peer_teacher_login %></td>
        <td><%= link_to 'Edit', edit_peer_teacher_login_path(peer_teacher_login) %></td>
        <td><%= link_to 'Destroy', peer_teacher_login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peer teacher login', new_peer_teacher_login_path %>

app/views/peer_teacher_logins/new.html.erb
<h1>New Peer Teacher Login</h1>

<%= render 'form' %>

<%= link_to 'Back', peer_teacher_logins_path %>

app/views/peer_teacher_logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @peer_teacher_login.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @peer_teacher_login.last_name %>
</p>

<%= link_to 'Edit', edit_peer_teacher_login_path(@peer_teacher_login) %> |
<%= link_to 'Back', peer_teacher_logins_path %>