config/routes.rb
Rails.application.routes.draw do
  resources :peer_teacher_logins
  resources :administrators
  ActiveAdmin.routes(self)
  
  devise_for :users, skip: :registrations, controllers: {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
    end
      
    get 'users/sign_out' => 'users/sessions#destroy'
    get 'users/sign_in'  => 'home#index'
    get 'users/password/edit' => 'users/password#edit'
  end
  
  get 'login_hub/index'                 #the index is for the regular user 
  get 'login_hub/admin'                 #for the admin page 
  
  get 'home/index'
  get 'home/populate_db'
  get 'home/availables'
  
  get '/ptc', to: 'ptc#ptc'
  get '/admin', to: 'admin#admin'
  get '/pt', to: 'pt#pt'

  root 'home#index' 

      resources :peer_teachers
      resources :office_hours
      resources :updates

end

app/controllers/login_hub_controller.rb
class LoginHubController < PeerTeacherController
  before_action :authenticate_user!
  before_action :after_sign_in_path_for
  #will be displayed in the /login_hub/index 
  def index
    #byebug
    @parent_user = current_user; 
    @user = PeerTeacherLogin.find( current_user.meta_id );
    
    @office_hours = OfficeHour.all
    @peer_teachers = PeerTeacher.all
    @updates = Update.all
    @time = Time.new
    @today = (@time.month.to_s + "/" + @time.day.to_s + "/" + @time.year.to_s)
    puts "********#{request.remote_ip}: logged into peer teacher hub using email: #{@user.first_name} "
  end
  
end

app/helpers/login_hub_helper.rb
module LoginHubHelper
end

app/views/login_hub/_cancel_hours.html.erb
<div class="row" style="margin: 20px;">
<div class="col-md-offset-2 col-md-8">
  <%= form_for :office_hour, url: office_hour_path(:office_hour), method: :put do |f| %>
    <%= f.hidden_field :userEmail, :value=>current_user.email %>
    <text>Date: </text>
    <br>
    <small-tab></small-tab>
    <text>Month: </text>
    <%= f.select(:cancelMonth, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], :selected => @time.month.to_s) %>
    <tab></tab>
    <text>Day: </text>
    <%= f.select(:cancelDay, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '31'], :selected => @time.day.to_s) %>
    <tab></tab>
    <text>Year: </text>
    <%= f.select(:cancelYear, ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2031', '2032', '2033', '2034', '2035', '2036', '2037', '2038', '2039', '2040'], :selected => @time.year.to_s) %>
    <br>
    <% @office_hours.where(email: current_user.email).find_each do |time| %>
      <small-tab></small-tab><%= f.radio_button :deleted, time.timeID.to_s%>
      <% timeDetails = beautify_time(time) %>
      <text><%= time.dow %> <%= timeDetails[0] %>:<%= timeDetails[1] %><%= timeDetails[2] %> - <%= timeDetails[3] %>:<%= timeDetails[4] %><%= timeDetails[5] %></text>
      <br>
    <% end %>
    <br>
    <text>I need to cancel my office hours because...</text>
    <br>
    <%= f.text_area :reason, :rows => 3, :placeholder => "I am cancelling my office hours because I have an interview at the same time.", :required => true %>
    <br>
    <br>
    <%= f.check_box :reschedule %>
    <text>Reschedule?</text>
    <br>
    <text>Date: </text>
    <br>
    <small-tab></small-tab>
    <text>Month: </text>
    <%= f.select(:rescheduleMonth, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], :selected => @time.month.to_s) %>
    <tab></tab>
    <text>Day: </text>
    <%= f.select(:rescheduleDay, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '31'], :selected => @time.day.to_s) %>
    <tab></tab>
    <text>Year: </text>
    <%= f.select(:rescheduleYear, ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2031', '2032', '2033', '2034', '2035', '2036', '2037', '2038', '2039', '2040'], :selected => @time.year.to_s) %>
    <br>
    <small-tab></small-tab>
    <text>Start Hour: </text>
    <%= f.select(:sHour, ['9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']) %>
    <tab></tab>
    <text>Start Minute: </text>
    <%= f.select(:sMin, ['00', '15', '30', '45'], {}, {}) %>
    <br>
    <small-tab></small-tab>
    <text>End Hour: </text>
    <%= f.select(:eHour, ['9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'], :selected => '10') %>
    <tab></tab>
    <text>End Minute: </text>
    <%= f.select(:eMin, ['00', '15', '30', '45'], {}, {}) %>
    <br>
    <p>
      <%= f.submit "Submit Change", :class => 'btn bar-btn' %>
    </p>
  <% end %>
</div>
</div>

app/views/login_hub/_change_view.html.erb
<div class="container-fluid text-center">
  <a id="back button" class="btn-link" onclick="return showPTDiv()">Go Back</a>
  <a id="cancel button" class="btn-link" onclick="return showCancelForm()">Cancel Hours</a>
  <a id="schedule button" class="btn-link" onclick="return showScheduleForm()">Schedule Hours</a>
</div>

<div id="cancel form">
  <%= render 'cancel_hours' %>
</div>

<div id="schedule form" style="display: none;">
  <%= render 'schedule_hours' %>
</div>

app/views/login_hub/_pt_view.html.erb
<div class="row" style="margin: 20px;">
<div class="col-md-offset-2 col-md-8">
  <sub-header>Hello <%= @user.first_name %> <%= @user.last_name %>,<br></sub-header>
  <br>
  <div class="container-fluid text-center">
    <a class="btn btn-link-active" onclick="return showChangeDiv()">Change Schedule</a> 
    <%#= link_to 'Take Survey',  "https://docs.google.com/forms/d/e/1FAIpQLScZDnwb9zo8OWxLvHuPCtaVVFFPW36CRdrJtD1XIfJR1LMt-w/viewform?usp=pp_url&entry.110379020=" + (@time - (60 * 60 * 5)).to_s[0..15] + "&entry.197140045=" + (@peer_teachers.find_by email: @parent_user.email).name + "&entry.11274062&entry.2071741446&entry.99313458", target: :_blank, class: 'btn btn-link-active'  %>
    <br>
  </div>
  <br>
  <sub-header>Hours: </sub-header>
  <br>
  <text id="hours">
    <%# Current User will have email, first_name, last_name email only %>
    <% @office_hours.where(email: @parent_user.email).find_each do |time| %>
      <% timeDetails = beautify_time(time) %>
      <tab></tab><%= time.dow %> <%= timeDetails[0] %>:<%= timeDetails[1] %><%= timeDetails[2] %> - <%= timeDetails[3] %>:<%= timeDetails[4] %><%= timeDetails[5] %>
      <br>
    <% end %>
  </text>
  <br>
  
  <sub-header>Changes: <br></sub-header>
    <% search = @updates.find_by_email(@parent_user.email)
      if search.blank? %>
        <tab></tab>
        <text>No upcoming schedule changes</text>
        <br>
      <% else %>
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-default">
              <tr>
                <th> </th>
                <th>Hours</th>
                <th>Approved?</th>
                <th>Reason</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @updates.where(email: @parent_user.email).find_each do |time| %>
              <tr>
                <td>
                  <% if (time.action == 'Delete') %>
                    -
                  <% else %>
                    +
                  <% end %>
                </td>
                <td>
                  <% timeDetails = beautify_time(time) %>
                  <%= time.dow %> <%= time.date %> @ <%= timeDetails[0] %>:<%= timeDetails[1] %><%= timeDetails[2] %> - <%= timeDetails[3] %>:<%= timeDetails[4] %><%= timeDetails[5] %></text>
                </td>
                <td>
                  <% if (time.approved == 1) %>
                    Yes
                  <% else %>
                    No
                  <% end %>
                </td>
                <td>
                  <%= time.msg %>
                </td>
                <td>
                  <%= link_to 'Delete', update_path(time), :class => 'btn btn-link-active', :method => :delete, :confirm => 'Are you sure?' %></text>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
    
    

  <sub-header>Courses: <br></sub-header>
  <text id="courses">
    <% @peer_teachers.where(email: @parent_user.email).find_each do |pt| %>
    <tab></tab>CSCE <%= pt.courselist %>
    <br>
    <% end %>
  </text>
</div>
</div>

app/views/login_hub/_schedule_hours.html.erb
<div class="row" style="margin: 20px;">
<div class="col-md-offset-2 col-md-8">
  <%= form_for :office_hour_add, url: office_hour_path(:office_hour_add), method: :put do |f| %>
    <%= f.hidden_field :userEmail, :value=>current_user.email %>
    <text>Date: </text>
    <br>
    <small-tab></small-tab>
    <text>Month: </text>
    <%= f.select(:rescheduleMonth, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], :selected => @time.month.to_s) %>
    <tab></tab>
    <text>Day: </text>
    <%= f.select(:rescheduleDay, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '31'], :selected => @time.day.to_s) %>
    <tab></tab>
    <text>Year: </text>
    <%= f.select(:rescheduleYear, ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2031', '2032', '2033', '2034', '2035', '2036', '2037', '2038', '2039', '2040'], :selected => @time.year.to_s) %>
    <br>
    <small-tab></small-tab>
    <text>Start Hour: </text>
    <%= f.select(:sHour, ['9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']) %>
    <tab></tab>
    <text>Start Minute: </text>
    <%= f.select(:sMin, ['00', '15', '30', '45'], {}, {}) %>
    <br>
    <small-tab></small-tab>
    <text>End Hour: </text>
    <%= f.select(:eHour, ['9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21'], :selected => '10') %>
    <tab></tab>
    <text>End Minute: </text>
    <%= f.select(:eMin, ['00', '15', '30', '45'], {}, {}) %>
    <br>
    <br>
    <text>I need to schedule office hours because...</text>
    <br>
    <%= f.text_area :reason, :rows => 3, :placeholder => "I am scheduling office hours because I had to cancel office hours last week.", :required => true %>
    <br>
    <p>
      <%= f.submit "Submit Change", :class => 'btn bar-btn' %>
    </p>
  <% end %>
</div>
</div>

app/views/login_hub/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta name="theme-color" content="#136D71"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="refresh" content="300" />
    
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/home.css" media="screen"/>
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    
    <script src="/assets/pt_login.js"></script>
    
    <!-- JQuery stuff for Calendar -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
      $( function() {
        $( "#cancelCalendar" ).datepicker();
      } );
      $( function() {
        $( "#rescheduleCalendar" ).datepicker();
      } );
    </script>

    <title>Peer Teacher Web Portal</title>
  </head>
  <body>
    <%= render 'navigation_bar' %>
    
    <!-- default view for peer teacher page -->
    <div id="pt view">
      <%= render 'pt_view' %>
    </div>
    
    <!-- view for changing scheduled office hours -->
    <div id="schedule change view" style="display: none">
      <%= render 'change_view' %>
    </div>
  </body>
</html>