config/routes.rb
Rails.application.routes.draw do
  resources :peer_teacher_logins
  resources :administrators
  ActiveAdmin.routes(self)
  
  devise_for :users, skip: :registrations, controllers: {
      :sessions => 'users/sessions',
      :passwords => 'users/passwords',
      :registrations => 'users/registrations'
  }
  
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'users/registrations',
      as: :user_registration do
        get :cancel
    end
      
    get 'users/sign_out' => 'users/sessions#destroy'
    get 'users/sign_in'  => 'home#index'
    get 'users/password/edit' => 'users/password#edit'
  end
  
  get 'login_hub/index'                 #the index is for the regular user 
  get 'login_hub/admin'                 #for the admin page 
  
  get 'home/index'
  get 'home/populate_db'
  get 'home/availables'
  
  get '/ptc', to: 'ptc#ptc'
  get '/admin', to: 'admin#admin'
  get '/pt', to: 'pt#pt'

  root 'home#index' 

      resources :peer_teachers
      resources :office_hours
      resources :updates

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
    has_one :user, as: :meta, dependent: :destroy 
    accepts_nested_attributes_for :user, allow_destroy: true 
    
    
end

app/controllers/administrators_controller.rb
class AdministratorsController < InheritedResources::Base

  #GET /administrators
  def index 
    @admin = Administrator.all  
  end

  #GET /administrators
  def show 
  end
  
  # GET /administrators/new
  def new 
    @admin = Administrator.new
    @admin.build_user
  end
  
  # GET /administratorss/1/edit 
  def edit
  end
  
  # POST /administrators
  def create 
    @admin = Administrator.new(administrator_params)
   
    respond_to do |format|
      if @admin.save
        format.html { redirect_to root_path, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /administrators/1
  def update
    respond_to do |format|
      if @admin.update(administrator_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /admnistrators/1 
  def destroy 
      @admin.destroy
      respond_to do |format|
          format.html { redirect_to teachers_url, notice: 'Admin was successfully destroyed.' }
          format.json { head :no_content }
      end 
  end

private
  
  def set_administrator
    @admin = Administrator.find( params[:id] )
  end

  def administrator_params
    params.require(:administrator).permit(:first_name, :last_name, user_attributes: [:id, :meta_id, :email, :password, :password_confirmation ])
  end
  
  def authenticate_administrator
    redirect_to( new_user_session_path) unless current_user.meta_type == "Administrator"
  end
  
  def new_registration
    redirect_to( administrators_path ) if user_signed_in?  
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Administrators</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.first_name %></td>
        <td><%= administrator.last_name %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @administrator.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @administrator.last_name %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>